# Generated by Django 6.1 on 2026-08-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CITIZEN', 'Citizen'), ('COMMUNITY_ORG', 'Community Organization'), ('GOVERNMENT_OFFICER', 'Government Officer'), ('UNIVERSITY', 'University Hub'), ('UNIVERSITY_ADMIN', 'University Admin'), ('FACULTY', 'Faculty Mentor'), ('STUDENT', 'Student Innovator'), ('INDUSTRY', 'Industry Partner'), ('STARTUP', 'Startup'), ('CSR_ORG', 'CSR Organization'), ('RESEARCH_LAB', 'Research Lab'), ('MENTOR', 'Mentor'), ('ADMIN', 'System Admin'), ('SUPER_ADMIN', 'Super Admin')], default='CITIZEN', max_length=30),
        ),
    ]
