# Generated by Django 6.1 on 2026-10-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_expertise_domain_user_tech_capabilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepting_projects',
            field=models.BooleanField(default=True, help_text='Uncheck if University/Industry is currently overloaded'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_or_logo',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='csr_budget_pool',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Available funding capacity', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_districts',
            field=models.CharField(blank=True, help_text='Comma-separated districts for local CSR matching', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='expertise_domain',
            field=models.TextField(blank=True, help_text='Comma-separated keywords for AI Matching (e.g., Traffic, Water, IoT)', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tech_capabilities',
            field=models.TextField(blank=True, help_text='Lab infrastructure or tech stack', null=True),
        ),
    ]
