# Generated by Django 6.1 on 2026-08-25 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('disaster', 'Disaster & Flooding'), ('infrastructure', 'Infrastructure & Roads'), ('water', 'Water & Sanitation'), ('electricity', 'Power & Electricity')], default='disaster', max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('evidence', models.ImageField(blank=True, null=True, upload_to='challenge_evidence/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', max_length=50)),
                ('priority', models.CharField(default='Medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_challenges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
