# Generated by Django 6.1 on 2026-08-29 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='assigned_university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challenge',
            name='proposal_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('forwarded_to_univ', 'Forwarded to University'), ('researching', 'University Researching'), ('proposal_submitted', 'Proposal Submitted'), ('in_progress', 'Implementation In Progress'), ('resolved', 'Resolved')], default='pending', max_length=50),
        ),
    ]
