# Generated by Django 6.1 on 2026-08-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_challenge_assigned_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='report_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of citizens reporting this same issue'),
        ),
    ]
