# Generated by Django 6.1 on 2026-09-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_challenge_report_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='action_logs',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
