# Generated by Django 6.1 on 2026-09-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_challenge_action_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='deployment_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='resolution_evidence',
            field=models.FileField(blank=True, null=True, upload_to='resolution_evidence/'),
        ),
    ]
