# Generated by Django 6.1 on 2026-09-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_challenge_deployment_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='deployment_notes',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='resolution_evidence',
        ),
        migrations.AddField(
            model_name='challenge',
            name='proposal_document',
            field=models.FileField(blank=True, null=True, upload_to='proposals/'),
        ),
    ]
