# Generated by Django 6.1 on 2026-08-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('district', models.CharField(max_length=100)),
                ('specialization_domains', models.JSONField(default=list, help_text="List of categories (e.g. ['water', 'infrastructure', 'disaster'])")),
                ('incubation_center', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('active_faculty_count', models.PositiveIntegerField(default=20)),
            ],
        ),
    ]
